In [1]:
import pandas as pd

In [2]:
data = pd.read_parquet("../data/raw/cars_raw.parquet")
data.head()

,id,title,year,mileage_km,transmission,fuel,price_egp,location,scraped_at
0,1,Deepal S 07 2025,2025.0,5000.0,Automatic,hybrid,1650000,"Sheikh Zayed, Giza•",2026-02-20 04:45:52
1,2,Chery Tiggo 2026,2026.0,NaN,Manual,petrol,915000,NaN,2026-02-20 04:50:40
2,3,Byd F3 2024,2024.0,4410.0,Manual,petrol,630000,"Ramses + Ramses Extension, Cairo•",2026-02-20 04:41:57
3,4,Byd F3 2025,2025.0,33033.0,Manual,petrol,610000,"Nasr City, Cairo•",2026-02-20 04:54:05
4,5,Subaru Impreza 2009,2009.0,98000.0,Manual,petrol,410000,"Maadi, Cairo•",2026-02-20 04:41:57

In [3]:
data.shape

(26895, 9)

In [4]:
data.describe()

,id,year,mileage_km,price_egp,scraped_at
count,26895.000000,26692.000000,2.684500e+04,2.689500e+04,26895
mean,13448.000000,2014.165743,1.783410e+05,4.134430e+09,2026-02-20 02:52:03.169950
min,1.000000,1950.000000,0.000000e+00,0.000000e+00,2026-02-20 00:31:03.528097
25%,6724.500000,2008.000000,2.400000e+04,3.000000e+05,2026-02-20 01:14:38.353081
50%,13448.000000,2016.000000,1.100000e+05,6.150000e+05,2026-02-20 02:16:37.957849
75%,20171.500000,2022.000000,1.950000e+05,1.250000e+06,2026-02-20 04:47:17
max,26895.000000,2027.000000,1.000000e+09,1.111111e+14,2026-02-20 04:58:20
std,7764.062081,9.896116,6.189675e+06,6.775194e+11,NaN